### PR TITLE
Add comparison other programs

### PR DESCRIPTION
**Pull request by JJK96**
Ref #5

### CODE REVIEW

**Comment by alexherbo2** [comment]
Can you use the same template as https://github.com/alexherbo2/krabby/blob/master/docs/alternatives.md?

**Comment by alexherbo2** [comment]
- [Batch processing]
- [Batch renaming]

[Batch processing]: https://en.wikipedia.org/wiki/Batch_processing
[Batch renaming]: https://en.wikipedia.org/wiki/Batch_renaming

**Comment by alexherbo2** [comment]
- [massren]

[massren]: https://github.com/laurent22/massren

**Comment by alexherbo2** [comment]
I added [nomino] to the list.

Maybe a more general PR could be more fitting?
The branch name could match, as you pushed to master, but the description needs to be updated.

[nomino]: https://github.com/yaa110/nomino

**Comment by JJK96** [comment]
You can merge this one, I don't know nonino, so I should not be the one to write the comparison at this point.

**Comment by alexherbo2** [comment]
The Markdown does not render well, and you removed information from the Krabby template.

https://github.com/alexherbo2/krabby/blob/master/docs/alternatives.md

**Comment by JJK96** [comment]
I removed the Type section, because I could not find a meaningful distinction in types, and the history section, because there is not any history yet.

I fixed the markdown rendering

**Comment by alexherbo2** [comment]
I’m ready to merge.  Can you squash the commits into a single one?

**Pull request merged**
